steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'jenkins/test-image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubekins-test:1.5', '-f=Dockerfile-1.5', '.']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'jenkins/test-image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubekins-test:1.6', '-f=Dockerfile-1.6', '.']

images: ['gcr.io/$PROJECT_ID/kubekins-test:1.5',
         'gcr.io/$PROJECT_ID/kubekins-test:1.6']
