steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'jenkins/test-image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubekins-test:1.4-$COMMIT_SHA', '-f=Dockerfile-1.4', '.']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'jenkins/test-image'
  args: ['tag', 'gcr.io/$PROJECT_ID/kubekins-test:1.4-$COMMIT_SHA', 'gcr.io/$PROJECT_ID/kubekins-test:1.4']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'jenkins/test-image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubekins-test:1.5-$COMMIT_SHA', '-f=Dockerfile-1.5', '.']

images: ['gcr.io/$PROJECT_ID/kubekins-test:1.4-$COMMIT_SHA',
         'gcr.io/$PROJECT_ID/kubekins-test:1.4',
         'gcr.io/$PROJECT_ID/kubekins-test:1.5-$COMMIT_SHA',
         ]
